# Generated by Django 5.0.7 on 2024-07-23 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePriceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('average_price', models.IntegerField()),
                ('updown', models.IntegerField(choices=[(0, 'Up'), (1, 'Down'), (2, 'Same')])),
                ('updown_percent', models.FloatField()),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='ChangePriceMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('average_price', models.IntegerField()),
                ('updown', models.IntegerField(choices=[(0, 'Up'), (1, 'Down'), (2, 'Same')])),
                ('updown_percent', models.FloatField()),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
            ],
        ),
    ]
