# Generated by Django 5.0.7 on 2024-07-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changepriceday',
            old_name='average_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='changepriceday',
            name='max',
        ),
        migrations.RemoveField(
            model_name='changepriceday',
            name='min',
        ),
        migrations.RemoveField(
            model_name='changepricemonth',
            name='max',
        ),
        migrations.RemoveField(
            model_name='changepricemonth',
            name='min',
        ),
    ]
